# Generated by Django 3.2.25 on 2024-08-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentid', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('addr1', models.CharField(blank=True, max_length=255, null=True)),
                ('addr2', models.CharField(blank=True, max_length=255, null=True)),
                ('areacode', models.CharField(blank=True, max_length=10, null=True)),
                ('sigungucode', models.CharField(blank=True, max_length=10, null=True)),
                ('mapx', models.FloatField(blank=True, null=True)),
                ('mapy', models.FloatField(blank=True, null=True)),
                ('modifiedtime', models.DateTimeField(blank=True, null=True)),
                ('firstimage', models.URLField(blank=True, null=True)),
                ('firstimage2', models.URLField(blank=True, null=True)),
                ('cat1', models.CharField(blank=True, max_length=10, null=True)),
                ('cat2', models.CharField(blank=True, max_length=10, null=True)),
                ('cat3', models.CharField(blank=True, max_length=10, null=True)),
                ('contenttypeid', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
