# Generated by Django 3.2.25 on 2024-07-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_customuser_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
