# Generated by Django 3.2.25 on 2024-07-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20240717_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
