# Generated by Django 3.2.25 on 2024-07-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20240728_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='levels_first',
            new_name='chosun',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='levels_second',
            new_name='goryeo',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='levels_third',
            new_name='modern',
        ),
        migrations.AddField(
            model_name='customuser',
            name='prehistoric',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='threeKingdoms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.CharField(blank=True, default='path/to/default/image.jpg', max_length=255, null=True),
        ),
    ]
