# Generated by Django 3.2.25 on 2024-07-28 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_customuser_nickname'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
