# Generated by Django 3.2.25 on 2024-07-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20240728_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.CharField(blank=True, default='/home/honglee0317/AiLearning/media/profile_default.png', max_length=255, null=True),
        ),
    ]
